##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:

build_scripts:
  - ./build-debs https://github.com/cafe-desktop/debian-packages cdkpixbuf cdk-pixbuf
  - cd `pkg-config --variable=cdk_pixbuf_binarydir cdk-pixbuf-2.0`
  - cd loaders
  - ls
  - cd ..
  - cat loaders.cache

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 ; fi
